Fix unknow error while try to print an error if a library could not be loaded

diff --git a/add_new_client b/add_new_client
--- a/add_new_client
+++ b/add_new_client
@@ -1,22 +1,38 @@
 #!/usr/bin/env bash
-#shellcheck disable=SC1091,SC2128,SC2154,SC2086,SC2034
+#shellcheck disable=SC1090,SC1091,SC2128,SC2154,SC2086,SC2034
 
-set -euo pipefail
+if [[ ! -r "$(dirname "$BASH_SOURCE")/networking.bash" ]]; then
+  echo "The core library networking.bash could not be found"
+  exit 4
+fi
 
-. "$(dirname "$BASH_SOURCE")/networking.bash" || echo "Could not find the networking library" && exit 4
-. "$(dirname "$BASH_SOURCE")/.env.dist" || echo "Could not find the .env configuration file" && exit 4
+env_paths=(
+  "$(dirname "$BASH_SOURCE")/.env"
+  ".env"
+)
+
+for env_file in "${env_paths[@]}"; do
+  if [[ -r "$env_file" ]]; then
+    . "$env_file"
+    break
+  else
+    unset "$env_file"
+  fi
+done
+
+if [[ -z "$env_file" ]]; then
+  echo "The '.env' configuration file, could not be found" >&2
+  exit 4
+fi
+
+. "$(dirname "$BASH_SOURCE")/networking.bash"
+. "$env_file"
 
 [[ $UID == 0 ]] || { echo "You must be root to run this."; exit 1; }
 
 # Options
 _d "Getting the options"
 while [[ $# -gt 0 ]]; do
-  _s peer_ip ""
-  _s peer_name
-  _s GENERATE_PEER_PSK true
-  _s is_behind_nat true
-  _s peer_local_networks
-  _s DEBUG false
   case $1 in
     -h|--help)
       echo
@@ -69,6 +85,14 @@ if [[ -z "${peer_ip:-}" ]]; then
 
   exit 4
 fi
+
+# Default values for variables
+_d "Setting default values"
+_s peer_name "${peer_name:-${peer_ip:-}}"
+_s GENERATE_PEER_PSK ${GENERATE_PEER_PSK:-true}
+_s is_behind_nat ${is_behind_nat:-true}
+_s peer_local_networks "${peer_local_networks:-}"
+_s DEBUG ${DEBUG:-false}
 
 # Configuration checks
 _d "Checking VPN Configuration"
